/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gui;

import datos.usuario;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class fMain extends javax.swing.JFrame {
    usuario usu;
    /** Creates new form fEmpleado */
    public fMain(usuario usu) {
        initComponents();
        this.usu = usu;
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        mnuUsuario.setText(usu.getNombre());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        mnuLogOut = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnuNuevaVenta = new javax.swing.JMenuItem();
        mnuGestionarVentas = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenu();
        mnuGestionarProductos = new javax.swing.JMenuItem();
        mnuProveedores = new javax.swing.JMenu();
        mnuGestionarProveedores = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        mnuGestionarEmpleados = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mnuGestionarClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda La Moda ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mnuUsuario.setText("Usuario");

        mnuLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuLogOut.setText("Cerrar sesion");
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuLogOut);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuSalir);

        jMenuBar1.add(mnuUsuario);

        mnuVentas.setText("Ventas");

        mnuNuevaVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuNuevaVenta.setText("Nueva");
        mnuNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaVentaActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuNuevaVenta);

        mnuGestionarVentas.setText("Gestionar");
        mnuGestionarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarVentasActionPerformed(evt);
            }
        });
        mnuVentas.add(mnuGestionarVentas);

        jMenuBar1.add(mnuVentas);

        mnuProductos.setText("Productos");

        mnuGestionarProductos.setText("Gestionar");
        mnuGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarProductosActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuGestionarProductos);

        jMenuBar1.add(mnuProductos);

        mnuProveedores.setText("Proveedores");

        mnuGestionarProveedores.setText("Gestionar");
        mnuGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarProveedoresActionPerformed(evt);
            }
        });
        mnuProveedores.add(mnuGestionarProveedores);

        jMenuBar1.add(mnuProveedores);

        mnuEmpleados.setText("Empleados");

        mnuGestionarEmpleados.setText("Gestionar");
        mnuGestionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarEmpleadosActionPerformed(evt);
            }
        });
        mnuEmpleados.add(mnuGestionarEmpleados);

        jMenuBar1.add(mnuEmpleados);

        mnuClientes.setText("Clientes");

        mnuGestionarClientes.setText("Gestionar");
        mnuGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGestionarClientesActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuGestionarClientes);

        jMenuBar1.add(mnuClientes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        nuevaVenta();
    }//GEN-LAST:event_formWindowOpened

    private void mnuNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaVentaActionPerformed
        nuevaVenta();
    }//GEN-LAST:event_mnuNuevaVentaActionPerformed

    private void mnuGestionarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarVentasActionPerformed
        new fVentas(this, false).setVisible(true);
    }//GEN-LAST:event_mnuGestionarVentasActionPerformed

    private void mnuGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarEmpleadosActionPerformed
        new fEmpleados(this, true).setVisible(true);
    }//GEN-LAST:event_mnuGestionarEmpleadosActionPerformed

    private void mnuGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarClientesActionPerformed
        new fClientes(this, true).setVisible(true);
    }//GEN-LAST:event_mnuGestionarClientesActionPerformed

    private void mnuGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarProveedoresActionPerformed
        new fProveedores(this, true).setVisible(true);
    }//GEN-LAST:event_mnuGestionarProveedoresActionPerformed

    private void mnuGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGestionarProductosActionPerformed
        new fProductos(this, true).setVisible(true);
    }//GEN-LAST:event_mnuGestionarProductosActionPerformed

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
        this.dispose();
        new fLogin(this).setVisible(true);
    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    void nuevaVenta(){
        fVenta v = new fVenta(usu);
        desktop.add(v);
        v.setVisible(true);
        v.requestFocus();
        try {
            v.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(fMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuEmpleados;
    private javax.swing.JMenuItem mnuGestionarClientes;
    private javax.swing.JMenuItem mnuGestionarEmpleados;
    private javax.swing.JMenuItem mnuGestionarProductos;
    private javax.swing.JMenuItem mnuGestionarProveedores;
    private javax.swing.JMenuItem mnuGestionarVentas;
    private javax.swing.JMenuItem mnuLogOut;
    private javax.swing.JMenuItem mnuNuevaVenta;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JMenu mnuProveedores;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuUsuario;
    private javax.swing.JMenu mnuVentas;
    // End of variables declaration//GEN-END:variables

}
